apiVersion: v1
kind: Pod
metadata:
  name: homework-webserver
  namespace: homework
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
    - name: config-volume
      configMap:
        name: nginx-site-conf
        items:
          - key: site.conf
            path: default.conf
  initContainers:
    - name: init-container
      image: busybox
      command: ["sh", "-c", "echo 'Hello from Homework' > /init/index.html"]
      volumeMounts:
        - name: shared-data
          mountPath: /init

  containers:
    - name: webserver-container
      image: nginx
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: shared-data
          mountPath: /homework
        - name: config-volume
          mountPath: /etc/nginx/conf.d
      lifecycle:
        preStop:
          exec:
            command: ["rm", "-f", "/homework/index.html"]

  restartPolicy: OnFailure
